# build stage
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# production nginx stage
FROM nginx:alpine
# copy built static files
COPY --from=build /app/dist /usr/share/nginx/html
# copy custom nginx config into container (overrides default)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
