# frontend/Dockerfile
# 1. Build stage
FROM node:20-alpine AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build   # ovo pravi dist folder

# 2. Nginx stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

# Ako treba custom config
# COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
